### ISSUE TITLE
Choosing the same file doesn't trigger onChange

### ISSUE THREAD

**Issue by sunnysingh** [ngokevin/react-file-reader-input#11]
This is only from initial testing, but wondering if anyone else can reproduce. Here is my scenario using similar markup as the readme:
1. Click "Select a file!" button and select `house.jpg`. This triggers onChange, everything is fine.
2. Click "Select a file!" button again and select `house.jpg` again. This **does not** trigger onChange. I would expect re-rendering would solve this issue but it doesn't.

This is a really weird issue so again I'm just wondering if this is an actual problem with the component itself.

**Comment by nickell** [comment]
@sunnysingh This is the default browser behavior. The `onChange` event only gets fired when something actually changes. This behavior is consistent across all HTML elements, `<input type="file" />` or `select` etc. What is it that you're trying to achieve?

**Comment by sunnysingh** [comment]
@nickell I have a button to reset my form and so when the user goes to choose another file, it shouldn't matter that they picked the same file. I will have to look further to see if this is an issue in my app, but it seems that re-rendering (even with `this.forceUpdate()`) still didn't trigger `onChange` for the same file. Normally for other inputs I am using controlled inputs, so am able to reset their values. Is it possible to do the same with react-file-reader-input?

**Comment by nickell** [comment]
@sunnysingh That's a good question. An input of type `file` can't be a controlled component in React because you can't set it's value attribute in HTML for security reasons. I don't really know what the best solution is here. One hacky way to do it would be to completely remove the file input component from the DOM during the form reset. Maybe some kind of `resetting` prop that you flip on and off that renders null when true?

**Comment by sunnysingh** [comment]
@nickell Thank you for the explanations. It's definitely hacky but I ended up doing what you suggested with removing the input from the DOM. If there's a cleaner or more proper way to do this please let me know, because I don't think my use case of resetting a form is that unique. Here's some sample code in case someone else stumbles upon this issue.

In the reset method (wherever the form is being reset):

``` javascript
// These can be separated, but I'm doing a callback to avoid setTimeout
this.setState({ resetting: true }, () => {
  this.setState({ resetting: false });
});
```

In `render()`:

``` javascript
{!this.state.resetting && (
  <FileReaderInput
    id="my-file-upload"
    onChange={this.handleFileChange}
  >
    <button>Select a file!</button>
  </FileReaderInput>
)}
```

**Comment by nickell** [comment]
@sunnysingh No problem, glad I could help! I agree that this isn't a unique use case. I'll comment here if I hear of or figure out a less hacky solution.

**Comment by eduardoturconi** [comment]
Another way to handle this is to set input value to ''.
It could be done on the `onChange` event:

    handleChange({target}) {
        const files = target.files
        target.value = ''
    }

**Comment by cuongluu8** [comment]
the `handleChange` approach does not work on IE11 and iOS9.  This is because when you update the target value it triggers another onChange event (seems like a bug in the browser).

My workaround was something like this
```
export function preventRecursiveEventHandler(eventHandler) {
    let recursive = false;

    return (...args) => {
        if (!recursive) {
            recursive = true;

            eventHandler.apply(this, args);

            recursive = false;
        }
    };
}

<input type="file" onClick="preventRecursiveEventHandler(handleChange)" />
```

**Comment by lfernando-silva** [comment]
The @eduardoturconi solution worked perfectly

**Comment by lakshmikanth-reddy-au2** [comment]
Thanks @eduardoturconi . It worked. Thanks again for the solution.

**Comment by pgalkevich** [comment]
Also, you can replace onChange by onInput.

**Comment by nx-amzzz** [comment]
```
// handleChange is executing as usual
// handleClick basically empty the target.value i.e. event.target.value = ""
const handleClick = event => {
    const { target = {} } = event || {};
    target.value = "";
  };

<input type="file" onChange={handleChange} onClick={handleClick} />
```

**Comment by manishkumar0282** [comment]
Thanks @eduardoturconi, it worked!!

**Comment by RizwanMushtaq** [comment]
thanks @nx-amzzz

**Comment by Natborks** [comment]
thanks @nx-amzzz

**Comment by ismailgunayy** [comment]
If we only add the `value=""` prop to the input, every time an onChange event occurs, the value is reset to an empty string. This results in onChange function works properly.

`<input type="file" onChange={handleChange} value="" />

**Comment by ismailgunayy** [comment]
I noticed that if we simply add the `value=""` attribute to the input, every time an onChange event occurs, the value gets reset to an empty string. This results in onChange function works properly.

`<input type="file" onChange={handleChange} value="" />`
