### ISSUE TITLE
move proptypes to use module proptypes (react 15.5.x)

### ISSUE THREAD

**Issue by jamuhl** [ngokevin/react-file-reader-input#13]
Consider using https://www.npmjs.com/package/prop-types to get rid off the react warnings about deprecating React.PropTypes in favour of new module.

**Comment by romor** [comment]
I also encounter a warning that seems to be related to this issue:
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by ngokevin** [comment]
done will update soon
