### ISSUE TITLE
Not compatible with react 16

### ISSUE THREAD

**Issue by bai1024** [ngokevin/react-file-reader-input#17]
Hey,
first of all thanks for the project. I got the following issue after I upgrade React to v16.0.0.
`npm WARN react-file-reader-input@1.1.4 requires a peer of react@^15.0.0 but none was installed.`
Any update regarding a new version that supports React 16?

**Comment by maximerety** [comment]
Fixed in https://github.com/ngokevin/react-file-reader-input/pull/18.

I'm not closing the issue until a new version is published on npm. @ngokevin Would you have any spare time to publish a new version soon?

**Comment by gausie** [comment]
This can now be closed! @maximerety
