### ISSUE TITLE
Get error message when init

### ISSUE THREAD

**Issue by cipherchien** [ngokevin/react-file-reader-input#2]
Hi,

I got the error message when init.

Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by ngokevin** [comment]
OK, I think I need to upgrade this component for newer versions of React.

**Comment by ngokevin** [comment]
Does https://github.com/ngokevin/react-file-reader-input/pull/4 work?
