### ISSUE TITLE
please bump peerDependency of react to allow v15.x.x

### ISSUE THREAD

**Issue by jamuhl** [ngokevin/react-file-reader-input#5]

**Comment by ngokevin** [comment]
Does this work with v15.x.x without further modifications? Might have to upgrade some stuff.

**Comment by jamuhl** [comment]
@ngokevin did not test...we got a rather large system with over 6 react client applications - just had time to check which modules are not react 15 read. If i get more time i might help checking out...but moving the migration from react 14 -> 15 is not highest prio on our list...more something that needs to be done somewhere in close future.

**Comment by reebalazs** [comment]
For what's worth:

I tested with 15.0, and it seems to work. My current use case is pretty simple though, so this does not prove that there can't be any problems ahead. In any case, it's worth to start testing.

https://github.com/ngokevin/react-file-reader-input/compare/master...reebalazs:master

**Comment by jamuhl** [comment]
giving up. just one more zombi module.

**Comment by ngokevin** [comment]
It's already been bumped, thanks for filing!
