### ISSUE TITLE
Warning: Unknown prop 'as'

### ISSUE THREAD

**Issue by vitalybe** [ngokevin/react-file-reader-input#7]
Here is the usage:

`<FileReaderInput as="binary" id="my-file-input" accept=".png,.gif,.jpg,.jpeg"
                             onChange={this.onImageChanged}>`

Here is the warning:

``````
warning.js?8a56:44Warning: Unknown prop `as` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by FileInput)
    in div (created by FileInput)
    in FileInput (created by HomePage)```
``````

**Comment by benlangfeld** [comment]
A fix for a similar problem was applied to another component at  https://github.com/captivationsoftware/react-sticky/commit/36efdea71ea6ebc2b9dce3ac0069c8ccd0c7879a and https://github.com/captivationsoftware/react-sticky/commit/4ec38e2efea97832427f2491f787a390e44af835

**Comment by 93xiaosi** [comment]
after the first click to cancel the upload,click again can not upload，why?

**Comment by benlangfeld** [comment]
Fixed in https://github.com/ngokevin/react-file-reader-input/commit/e82ddd3327bf823c9dae334db3b0474d32109cb0
